query getSchedulerPrograms($programsList: [ProgramId!]) {
  programs(WHERE: { id: { IN: $programsList } }) {
    matches {
      id
      name
      description
      existence
      type
      reference {
        label
        type
      }
      active {
        start
        end
      }
      proposalStatus
      proposal {
        ...SchedulerProposal
      }
      allocations {
        category
        duration {
          hours
        }
        scienceBand
      }
      timeCharge {
        band
        time {
          program {
            hours
          }
          total {
            hours
          }
          nonCharged {
            hours
          }
        }
      }
      allGroupElements {
        parentGroupId
        group {
          id
          name
          minimumRequired
          ordered
          parentId
          parentIndex
          minimumInterval {
            seconds
          }
          maximumInterval {
            seconds
          }
          system
        }
        observation {
          id
          groupId
        }
      }
    }
  }
}

query getSchedulerProgramIds($today: Date) {
  programs(
    WHERE: {
      activeEnd: { GTE: $today }
      activeStart: { LT: $today }
      OR: [
        { proposalStatus: { EQ: ACCEPTED } }
        { type: { IN: [CALIBRATION, ENGINEERING] } }
      ]
    }
  ) {
    matches {
      reference {
        label
      }
      id
    }
  }
}
