# Generated by `python -m codegen generate`. DO NOT EDIT.
# mypy: ignore-errors

from __future__ import annotations

from datetime import UTC, date, datetime
from typing import Annotated

from pydantic import PlainSerializer


def _utc_z(value: datetime) -> str:
    """Serialize a datetime as an ISO-8601 UTC instant with a Z suffix."""
    if value.tzinfo is None:
        value = value.replace(tzinfo=UTC)
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


Timestamp = Annotated[datetime, PlainSerializer(_utc_z, when_used="json")]
"""An instant in time, serialized as an ISO-8601 UTC string."""

AtomId = str
"""AtomId id formatted as `a-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`"""
AttachmentId = str
"""AttachmentId id formatted as `a-[1-9a-f][0-9a-f]*`"""
BigDecimal = float
"""The `BigDecimal` scalar type represents signed fractional values with arbitrary precision."""
CallForProposalsId = str
"""Defines a unique ID for each Call for Proposals."""
ChronicleId = str
ConfigurationRequestId = str
DatasetFilename = str
"""Dataset filename in standard format."""
DatasetId = str
"""DatasetId id formatted as `d-[1-9a-f][0-9a-f]*`"""
DatasetReferenceLabel = str
"""Dataset reference, formatted according to the observation, suffixed with"""
Date = date
"""Date in ISO-8601 representation in format YYYY-MM-DD (e.g., '2024-07-31')."""
DmsString = str
"""Target declination coordinate in format '[+/-]DD:MM:SS.sss'"""
EmailAddress = str
"""Email address, matching ^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}$"""
EpochString = str
"""Reference observation epoch in format '[JB]YYYY.YYY'"""
ExecutionEventId = str
"""ExecutionEventId id formatted as `e-[1-9a-f][0-9a-f]*`"""
Extinction = float
"""Non-negative floating-point value."""
GroupId = str
HmsString = str
"""Target right ascension coordinate in format 'HH:MM:SS.sss'"""
IdempotencyKey = str
"""A UUID provided by a client in order to prevent retrying a failed mutation from"""
IntPercent = int
"""An 'Int` in the range 0 to 100"""
Long = int
"""The `Long` scalar type represents non-fractional signed whole numeric values. Long can represent values between -(2^63) and 2^63 - 1."""
NonEmptyString = str
"""A String value that cannot be empty"""
NonNegBigDecimal = float
"""A `BigDecimal` greater than or equal to 0"""
NonNegInt = int
"""An `Int` in the range from 0 to 2147483647"""
NonNegLong = int
"""An `Long` in the range from 0 to 9223372036854775807"""
NonNegShort = int
"""A `Short` in the range from 0 to 32767"""
ObservationId = str
"""ObservationId id formatted as `o-[1-9a-f][0-9a-f]*`"""
ObservationReferenceLabel = str
"""Observation reference, formatted according to the program type, suffixed with"""
PosBigDecimal = float
"""A `BigDecimal` greater than 0"""
PosInt = int
"""An `Int` in the range from 1 to 2147483647"""
PosLong = int
"""An `Long` in the range from 1 to 9223372036854775807"""
PosShort = int
"""A `Short` in the range from 1 to 32767"""
ProgramId = str
"""ProgramId id formatted as `p-[1-9a-f][0-9a-f]*`"""
ProgramNoteId = str
"""ProgramNoteId is formated as `n-[1-9a-f][0-9a-f]*`"""
ProgramReferenceLabel = str
"""Program reference, formatted according to the type.  For example, a Science"""
ProgramUserId = str
ProposalReferenceLabel = str
"""Proposal reference for science programs, formatted as G-YYYY[AB]-NNNN+. For"""
Semester = str
"""Semester string (from 2000A) in the format YYYY[AB].  An abbreviated format,"""
SignalToNoise = float
StepId = str
"""StepId id formatted as `s-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`"""
TargetId = str
"""TargetId id formatted as `t-[1-9a-f][0-9a-f]*`"""
TransactionId = str
UserId = str
UserInvitationId = str
UserInvitationKey = str
VisitId = str
"""VisitId id formatted as `v-[1-9a-f][0-9a-f]*`"""

__all__ = ['AtomId', 'AttachmentId', 'BigDecimal', 'CallForProposalsId', 'ChronicleId', 'ConfigurationRequestId', 'DatasetFilename', 'DatasetId', 'DatasetReferenceLabel', 'Date', 'DmsString', 'EmailAddress', 'EpochString', 'ExecutionEventId', 'Extinction', 'GroupId', 'HmsString', 'IdempotencyKey', 'IntPercent', 'Long', 'NonEmptyString', 'NonNegBigDecimal', 'NonNegInt', 'NonNegLong', 'NonNegShort', 'ObservationId', 'ObservationReferenceLabel', 'PosBigDecimal', 'PosInt', 'PosLong', 'PosShort', 'ProgramId', 'ProgramNoteId', 'ProgramReferenceLabel', 'ProgramUserId', 'ProposalReferenceLabel', 'Semester', 'SignalToNoise', 'StepId', 'TargetId', 'Timestamp', 'TransactionId', 'UserId', 'UserInvitationId', 'UserInvitationKey', 'VisitId']
