"""
Emit pydantic models from the merged schema.

One module per kind: scalars (type aliases), enums (StrEnum), inputs
(pydantic models with omit-when-unset semantics), and models (one output
model per object/interface type, plus discriminated-union aliases for
abstract types).

Output models declare each field with its natural GraphQL type but default
every field to the UNSET sentinel: a field the operation did not select stays
UNSET, which is distinct from a server-returned null.
"""

from gqlforge import GqlforgeError
from gqlforge.config import Config
from gqlforge.naming import python_enum_member, python_field_name
from graphql import (
    GraphQLEnumType,
    GraphQLInputObjectType,
    GraphQLInterfaceType,
    GraphQLList,
    GraphQLNonNull,
    GraphQLObjectType,
    GraphQLScalarType,
    GraphQLSchema,
    GraphQLUnionType,
)

GENERATED_HEADER = """\
# Generated by `gqlforge generate`. DO NOT EDIT.
# mypy: ignore-errors
"""

BUILTIN_SCALARS = {
    "String": "str",
    "Int": "int",
    "Float": "float",
    "Boolean": "bool",
    "ID": "str",
}

# Custom scalars with a non-str Python representation. Everything absent from
# this table maps to ``str``; scalars the emitter has never seen are also
# reported so a schema refresh cannot silently mistype a new one.
KNOWN_SCALARS = {
    # Integral.
    "Long": "int",
    "PosLong": "int",
    "NonNegLong": "int",
    "PosInt": "int",
    "NonNegInt": "int",
    "PosShort": "int",
    "NonNegShort": "int",
    "IntPercent": "int",
    # Decimal. float matches the JSON wire format; astronomy magnitudes fit.
    "BigDecimal": "float",
    "NonNegBigDecimal": "float",
    "PosBigDecimal": "float",
    "SignalToNoise": "float",
    "Extinction": "float",
    # Temporal. Timestamp is an Annotated[datetime] defined in scalars.py.
    "Date": "date",
}

KNOWN_STRING_SCALARS = {
    "AtomId",
    "AttachmentId",
    "CallForProposalsId",
    "ChronicleId",
    "ConfigurationRequestId",
    "DatasetFilename",
    "DatasetId",
    "DatasetReferenceLabel",
    "DmsString",
    "EmailAddress",
    "EpochString",
    "ExecutionEventId",
    "GroupId",
    "HmsString",
    "IdempotencyKey",
    "NonEmptyString",
    "ObservationId",
    "ObservationReferenceLabel",
    "ProgramId",
    "ProgramNoteId",
    "ProgramReferenceLabel",
    "ProgramUserId",
    "ProposalReferenceLabel",
    "Semester",
    "StepId",
    "TargetId",
    "TooTriggerId",
    "TransactionId",
    "UserId",
    "UserInvitationId",
    "UserInvitationKey",
    "VisitId",
}


def _line_doc(text: str) -> str:
    """A one-line docstring statement for a module-level alias."""
    first = text.strip().splitlines()[0] if text.strip() else ""
    clean = first.replace("\\", "\\\\").replace('"""', "'''").rstrip('"')
    return f'"""{clean}"""'


def _docstring(text: str | None, indent: str = "    ") -> list[str]:
    """Render a description as a docstring block, or nothing."""
    if not text:
        return []
    clean = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"').strip()
    lines = clean.splitlines()
    if len(lines) == 1 and not lines[0].endswith('"'):
        return [f'{indent}"""{lines[0]}"""']
    body = [f'{indent}"""']
    body.extend(f"{indent}{line}".rstrip() for line in lines)
    body.append(f'{indent}"""')
    return body


def render_type(gql_type, *, nullable_suffix: bool = True) -> str:
    """Render a GraphQL type as a Python annotation string."""
    if isinstance(gql_type, GraphQLNonNull):
        return render_type(gql_type.of_type, nullable_suffix=False)
    if isinstance(gql_type, GraphQLList):
        inner = render_type(gql_type.of_type)
        rendered = f"list[{inner}]"
    else:
        rendered = gql_type.name
        if isinstance(gql_type, GraphQLScalarType) and gql_type.name in BUILTIN_SCALARS:
            rendered = BUILTIN_SCALARS[gql_type.name]
    if nullable_suffix:
        rendered += " | None"
    return rendered


def scalar_python_type(name: str, warnings: list[str]) -> str:
    """Python type for a custom scalar, warning on unrecognized names."""
    if name in KNOWN_SCALARS:
        return KNOWN_SCALARS[name]
    if name == "Timestamp":
        return "Timestamp"
    if name not in KNOWN_STRING_SCALARS:
        warnings.append(
            f"Scalar '{name}' is not in codegen/emit_models.py's scalar table; "
            "mapping it to str. Add it to KNOWN_SCALARS or "
            "KNOWN_STRING_SCALARS."
        )
    return "str"


def emit_scalars(schema: GraphQLSchema, warnings: list[str]) -> str:
    """Emit scalars.py: one alias per custom scalar."""
    lines = [
        GENERATED_HEADER,
        "from __future__ import annotations",
        "",
        "from datetime import UTC, date, datetime",
        "from typing import Annotated",
        "",
        "from pydantic import PlainSerializer",
        "",
        "",
        "def _utc_z(value: datetime) -> str:",
        '    """Serialize a datetime as an ISO-8601 UTC instant with a Z suffix."""',
        "    if value.tzinfo is None:",
        "        value = value.replace(tzinfo=UTC)",
        '    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")',
        "",
        "",
        'Timestamp = Annotated[datetime, PlainSerializer(_utc_z, when_used="json")]',
        '"""An instant in time, serialized as an ISO-8601 UTC string."""',
        "",
    ]
    names = ["Timestamp"]
    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if not isinstance(gql_type, GraphQLScalarType):
            continue
        if name.startswith("__") or name in BUILTIN_SCALARS or name == "Timestamp":
            continue
        python_type = scalar_python_type(name, warnings)
        lines.append(f"{name} = {python_type}")
        if gql_type.description:
            lines.append(_line_doc(gql_type.description))
        names.append(name)
    lines.append("")
    lines.append(f"__all__ = {sorted(names)!r}")
    lines.append("")
    return "\n".join(lines)


def emit_enums(schema: GraphQLSchema) -> str:
    """Emit enums.py: one StrEnum per GraphQL enum."""
    lines = [
        GENERATED_HEADER,
        "from enum import StrEnum",
        "",
    ]
    names = []
    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if not isinstance(gql_type, GraphQLEnumType) or name.startswith("__"):
            continue
        names.append(name)
        lines.append("")
        lines.append(f"class {name}(StrEnum):")
        lines.extend(_docstring(gql_type.description))
        for value_name in gql_type.values:
            member = python_enum_member(value_name)
            lines.append(f'    {member} = "{value_name}"')
        lines.append("")
    lines.append(f"__all__ = {sorted(names)!r}")
    lines.append("")
    return "\n".join(lines)


def _check_field_collisions(type_name: str, field_names: dict[str, str]) -> None:
    """Fail when two GraphQL fields map to the same Python name."""
    seen: dict[str, str] = {}
    for graphql_name, python_name in field_names.items():
        if python_name in seen:
            raise GqlforgeError(
                f"Fields '{seen[python_name]}' and '{graphql_name}' on "
                f"'{type_name}' both map to Python name '{python_name}'."
            )
        seen[python_name] = graphql_name


def _rebuild_loop(tuple_name: str, variable: str) -> list[str]:
    """
    The eager forward-ref resolution loop emitted at module tail.

    Deeply mutual type graphs (GitHub's schema) exceed Python's default
    recursion limit inside pydantic's schema builder, so the limit is
    raised around the loop and always restored.
    """
    return [
        "_RECURSION_LIMIT = sys.getrecursionlimit()",
        "sys.setrecursionlimit(max(_RECURSION_LIMIT, 3000))",
        "try:",
        f"    for {variable} in {tuple_name}:",
        f"        {variable}.model_rebuild()",
        "finally:",
        "    sys.setrecursionlimit(_RECURSION_LIMIT)",
    ]


def emit_inputs(schema: GraphQLSchema, config: Config) -> str:
    """Emit inputs.py: pydantic models for every input object type."""
    lines = [
        GENERATED_HEADER,
        "from __future__ import annotations",
        "",
        "import sys",
        "",
        "from pydantic import Field",
        "",
        f"from {config.runtime_package}._base import {config.input_base}",
        f"from {config.generated_package}.enums import *  # noqa: F401,F403",
        f"from {config.generated_package}.scalars import *  # noqa: F401,F403",
        "",
    ]
    names = []
    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if not isinstance(gql_type, GraphQLInputObjectType) or name.startswith("__"):
            continue
        names.append(name)
        lines.append("")
        lines.append(f"class {name}({config.input_base}):")
        lines.extend(_docstring(gql_type.description))
        mapping = {g: python_field_name(g) for g in gql_type.fields}
        _check_field_collisions(name, mapping)
        for field_name, field_def in gql_type.fields.items():
            python_name = mapping[field_name]
            has_default = (
                field_def.ast_node is not None
                and field_def.ast_node.default_value is not None
            )
            required = isinstance(field_def.type, GraphQLNonNull) and not has_default
            annotation = render_type(field_def.type)
            alias = (
                f'validation_alias="{field_name}", serialization_alias="{field_name}"'
                if python_name != field_name
                else None
            )
            if required:
                suffix = f" = Field({alias})" if alias else ""
                lines.append(f"    {python_name}: {annotation}{suffix}")
            else:
                if not annotation.endswith("| None"):
                    annotation += " | None"
                if alias:
                    lines.append(
                        f"    {python_name}: {annotation} = "
                        f"Field(default=None, {alias})"
                    )
                else:
                    lines.append(f"    {python_name}: {annotation} = None")
        if not gql_type.fields:
            lines.append("    pass")
        lines.append("")
    lines.append("")
    if names:
        lines.append(f"_INPUT_TYPES = ({', '.join(names)},)")
    else:
        lines.append("_INPUT_TYPES = ()")
    lines.extend(_rebuild_loop("_INPUT_TYPES", "_input_type"))
    lines.append("")
    lines.append(f"__all__ = {sorted(names)!r}")
    lines.append("")
    return "\n".join(lines)


def _implementors(schema: GraphQLSchema, interface: GraphQLInterfaceType) -> list[str]:
    """Concrete object types implementing an interface, sorted by name."""
    return sorted(
        t.name
        for t in schema.type_map.values()
        if isinstance(t, GraphQLObjectType) and interface in t.interfaces
    )


def emit_output_models(schema: GraphQLSchema, config: Config) -> str:
    """Emit models.py: output models plus abstract-type union aliases."""
    root_names = {
        t.name
        for t in (schema.query_type, schema.mutation_type, schema.subscription_type)
        if t is not None
    }

    lines = [
        GENERATED_HEADER,
        "from __future__ import annotations",
        "",
        "import sys",
        "from typing import Annotated, Literal",
        "",
        "from pydantic import Field",
        "",
        f"from {config.runtime_package}._base import UNSET, {config.model_base}",
        f"from {config.generated_package}.enums import *  # noqa: F401,F403",
        f"from {config.generated_package}.scalars import *  # noqa: F401,F403",
        "",
    ]

    class_names: list[str] = []
    alias_lines: list[str] = []
    alias_names: list[str] = []

    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if name.startswith("__") or name in root_names:
            continue

        if isinstance(gql_type, GraphQLUnionType):
            # Root operation types are never emitted as models, so they
            # cannot appear in an alias (GitHub's Query implements Node).
            members = sorted(t.name for t in gql_type.types if t.name not in root_names)
            if not members:
                continue
            alias_names.append(name)
            alias_lines.append("")
            if len(members) == 1:
                alias_lines.append(f"{name} = {members[0]}")
            else:
                alias_lines.append(f"{name} = Annotated[")
                alias_lines.append(f"    {' | '.join(members)},")
                alias_lines.append('    Field(discriminator="typename"),')
                alias_lines.append("]")
            if gql_type.description:
                alias_lines.append(_line_doc(gql_type.description))
            continue

        if isinstance(gql_type, GraphQLInterfaceType):
            members = [
                m for m in _implementors(schema, gql_type) if m not in root_names
            ]
            if members:
                alias_names.append(name)
                alias_lines.append("")
                if len(members) == 1:
                    alias_lines.append(f"{name} = {members[0]}")
                else:
                    alias_lines.append(f"{name} = Annotated[")
                    alias_lines.append(f"    {' | '.join(members)},")
                    alias_lines.append('    Field(discriminator="typename"),')
                    alias_lines.append("]")
                if gql_type.description:
                    alias_lines.append(_line_doc(gql_type.description))
                continue
            # An interface with no implementors degrades to a plain model.

        if not isinstance(gql_type, (GraphQLObjectType, GraphQLInterfaceType)):
            continue

        class_names.append(name)
        lines.append("")
        lines.append(f"class {name}({config.model_base}):")
        lines.extend(_docstring(gql_type.description))
        lines.append(
            f'    typename: Literal["{name}"] = Field('
            f'default="{name}", validation_alias="__typename", '
            f'serialization_alias="__typename")'
        )
        mapping = {g: python_field_name(g) for g in gql_type.fields}
        mapping["__typename"] = "typename"
        _check_field_collisions(name, mapping)
        del mapping["__typename"]
        for field_name, field_def in gql_type.fields.items():
            python_name = mapping[field_name]
            annotation = render_type(field_def.type)
            if python_name != field_name:
                lines.append(
                    f"    {python_name}: {annotation} = Field(default=UNSET, "
                    f'validation_alias="{field_name}", '
                    f'serialization_alias="{field_name}")'
                )
            else:
                lines.append(f"    {python_name}: {annotation} = UNSET")
        lines.append("")

    lines.extend(alias_lines)
    lines.append("")
    lines.append("_MODEL_TYPES = (")
    for name in class_names:
        lines.append(f"    {name},")
    lines.append(")")
    lines.extend(_rebuild_loop("_MODEL_TYPES", "_model_type"))
    lines.append("")
    lines.append(f"__all__ = {sorted(class_names + alias_names)!r}")
    lines.append("")
    return "\n".join(lines)
