"""
Codegen pipeline orchestration: generate, check, readiness, download.
"""

import json
import subprocess

from codegen import (
    AVAILABILITY_PATH,
    GENERATED_DIR,
    MERGED_SCHEMA_PATH,
    REPO_ROOT,
    SCHEMAS_DIR,
    CodegenError,
)
from codegen.emit_models import (
    emit_enums,
    emit_inputs,
    emit_output_models,
    emit_scalars,
)
from codegen.emit_operations import (
    build_operation_specs,
    emit_domains,
    emit_operation_map,
)
from codegen.operations import inject_typename, load_operations, validate_operations
from codegen.prune import prune_document_for_schema
from codegen.schema import (
    build_schema,
    discover_sources,
    download_schema_sdl,
    field_availability,
    load_schema_document,
    merge_schema_documents,
)
from graphql import print_ast

GENERATED_PATHS = (GENERATED_DIR, MERGED_SCHEMA_PATH, AVAILABILITY_PATH)


def run_generate() -> None:
    """Execute the full generation pipeline."""
    sources = discover_sources()
    print(f"Schema sources (newest first): {', '.join(sources)}")

    documents = {s: load_schema_document(s) for s in sources}
    merged_document, divergences = merge_schema_documents(documents, list(sources))

    structural = [d for d in divergences if d.kind == "structural"]
    for divergence in structural:
        rendered = ", ".join(f"{s}={t}" for s, t in divergence.types.items())
        print(
            f"WARNING structural divergence (kept newest): "
            f"{divergence.location}: {rendered}"
        )

    merged_schema = build_schema(merged_document)
    loaded = load_operations()
    union_document = inject_typename(loaded.document, merged_schema)

    # A selection invalid against the merged (union) schema is valid nowhere.
    errors = validate_operations(merged_schema, union_document)
    if errors:
        raise CodegenError(
            "Operations do not validate against ANY environment:\n  "
            + "\n  ".join(errors)
        )

    schemas = {s: build_schema(documents[s]) for s in sources}
    prune_results = {
        s: prune_document_for_schema(union_document, schemas[s]) for s in sources
    }

    # Structural divergences are fatal only when our operations select them.
    selected: set[str] = set()
    for result in prune_results.values():
        selected |= {location for location, _ in result.dropped}
    blocking = [d for d in structural if d.location in selected]
    if blocking:
        raise CodegenError(
            "Operations select structurally divergent fields; a human must "
            "resolve these:\n  " + "\n  ".join(d.location for d in blocking)
        )

    # Every per-source pruned document must validate against its own schema.
    for source in sources:
        source_errors = validate_operations(
            schemas[source], prune_results[source].document
        )
        if source_errors:
            raise CodegenError(
                f"Pruned document for '{source}' does not validate (codegen "
                "bug):\n  " + "\n  ".join(source_errors)
            )

    specs = build_operation_specs(union_document, merged_schema, loaded.domains)

    scalar_warnings: list[str] = []
    outputs = {
        GENERATED_DIR / "scalars.py": emit_scalars(merged_schema, scalar_warnings),
        GENERATED_DIR / "enums.py": emit_enums(merged_schema),
        GENERATED_DIR / "inputs.py": emit_inputs(merged_schema),
        GENERATED_DIR / "models.py": emit_output_models(merged_schema),
        GENERATED_DIR / "operations.py": emit_operation_map(
            specs, prune_results, schemas, list(sources)
        ),
        GENERATED_DIR / "domains.py": emit_domains(specs),
    }
    for warning in scalar_warnings:
        print(f"WARNING {warning}")

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init_path = GENERATED_DIR / "__init__.py"
    if not init_path.exists():
        init_path.write_text(
            '"""Generated by `python -m codegen generate`. DO NOT EDIT."""\n',
            encoding="utf-8",
        )
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")

    MERGED_SCHEMA_PATH.write_text(print_ast(merged_document), encoding="utf-8")
    print(f"Wrote {MERGED_SCHEMA_PATH.relative_to(REPO_ROOT)}")

    manifest = {
        "sources": list(sources),
        "operations": {
            spec.name: sorted(
                s for s in sources if spec.name in prune_results[s].operations
            )
            for spec in sorted(specs, key=lambda s: s.name)
        },
        "fields": {
            pair: list(avail)
            for pair, avail in field_availability(schemas, sources).items()
        },
    }
    AVAILABILITY_PATH.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"Wrote {AVAILABILITY_PATH.relative_to(REPO_ROOT)}")

    for source in sources:
        result = prune_results[source]
        pruned_fields = sorted({location for location, _ in result.dropped})
        if pruned_fields:
            print(
                f"{source}: pruned {len(pruned_fields)} selection(s): "
                + ", ".join(pruned_fields)
            )
        if result.dead_operations:
            print(
                f"{source}: unavailable operation(s): "
                + ", ".join(result.dead_operations)
            )


def run_check() -> None:
    """Run generate and fail if any committed artifact changed."""
    run_generate()
    paths = [str(p) for p in GENERATED_PATHS]
    diff = subprocess.run(
        ["git", "diff", "--exit-code", "--stat", "--", *paths],
        cwd=REPO_ROOT,
    )
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard", "--", *paths],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if diff.returncode != 0 or untracked.stdout.strip():
        if untracked.stdout.strip():
            print("Untracked generated files:\n" + untracked.stdout)
        raise CodegenError(
            "Generated artifacts are stale. Run "
            "'uv run python -m codegen generate' and commit the result."
        )
    print("Generated artifacts are up to date.")


def run_readiness() -> int:
    """Print the promotion-readiness report. Returns an exit code."""
    sources = discover_sources()
    if len(sources) < 2:
        print("Only one schema source committed; nothing to compare.")
        return 0

    schemas = {s: build_schema(load_schema_document(s)) for s in sources}
    newest, oldest = sources[0], sources[-1]

    def field_map(schema):
        pairs = set()
        for type_name, graphql_type in schema.type_map.items():
            if type_name.startswith("__"):
                continue
            for field_name in getattr(graphql_type, "fields", None) or {}:
                pairs.add(f"{type_name}.{field_name}")
            for value_name in getattr(graphql_type, "values", None) or {}:
                pairs.add(f"{type_name}.{value_name}")
        return pairs

    newest_map, oldest_map = field_map(schemas[newest]), field_map(schemas[oldest])

    # What do our operations actually touch? Selected pairs are those pruning
    # keeps in at least one environment plus those it drops somewhere.
    documents = {s: load_schema_document(s) for s in sources}
    merged_document, divergences = merge_schema_documents(documents, list(sources))
    merged_schema = build_schema(merged_document)
    union_document = inject_typename(load_operations().document, merged_schema)
    selected: set[str] = set()
    for source in sources:
        result = prune_document_for_schema(union_document, schemas[source])
        selected |= {location for location, _ in result.dropped}
        selected |= _kept_pairs(result, schemas[source])

    ahead = sorted(newest_map - oldest_map)
    removed = sorted(oldest_map - newest_map)
    ahead_selected = [p for p in ahead if p in selected]
    removed_selected = [p for p in removed if p in selected]
    structural = [d for d in divergences if d.kind == "structural"]
    structural_selected = [d for d in structural if d.location in selected]

    print(f"chain: {' > '.join(sources)} (newest first)")
    print()
    print("AUTO - handled by codegen")
    print(
        f"  ahead in {newest}, absent in {oldest}: {len(ahead)} "
        f"({len(ahead_selected)} selected)"
    )
    for pair in ahead_selected:
        print(f"    {pair}")
    print("WATCH - works today, breaks when production catches up")
    print(
        f"  removed in {newest}, still in {oldest}: {len(removed)} "
        f"({len(removed_selected)} selected)"
    )
    for pair in removed_selected:
        print(f"    {pair}")
    print("BLOCKED - needs a human")
    print(
        f"  structural type changes: {len(structural)} "
        f"({len(structural_selected)} selected)"
    )
    for divergence in structural:
        marker = "SELECTED" if divergence in structural_selected else "unused"
        rendered = ", ".join(f"{s}={t}" for s, t in divergence.types.items())
        print(f"    [{marker}] {divergence.location}: {rendered}")

    if structural_selected:
        print("FAIL: blocking divergences touch the operation set.")
        return 1
    print("OK: no blocking items touch the operation set.")
    return 0


def _kept_pairs(result, schema) -> set[str]:
    """Type.field pairs a pruned document still selects."""
    from graphql import (
        FieldNode,
        FragmentDefinitionNode,
        FragmentSpreadNode,
        InlineFragmentNode,
        OperationDefinitionNode,
        get_named_type,
    )

    pairs: set[str] = set()
    fragments = result.fragments

    def walk(selection_set, parent_type, seen):
        if selection_set is None or parent_type is None:
            return
        fields = getattr(parent_type, "fields", None)
        for selection in selection_set.selections:
            if isinstance(selection, FieldNode):
                if selection.name.value == "__typename":
                    continue
                if not fields or selection.name.value not in fields:
                    continue
                pairs.add(f"{parent_type.name}.{selection.name.value}")
                walk(
                    selection.selection_set,
                    get_named_type(fields[selection.name.value].type),
                    seen,
                )
            elif isinstance(selection, InlineFragmentNode):
                target = (
                    schema.type_map.get(selection.type_condition.name.value)
                    if selection.type_condition
                    else parent_type
                )
                walk(selection.selection_set, target, seen)
            elif isinstance(selection, FragmentSpreadNode):
                name = selection.name.value
                if name in fragments and name not in seen:
                    seen.add(name)
                    fragment = fragments[name]
                    walk(
                        fragment.selection_set,
                        schema.type_map.get(fragment.type_condition.name.value),
                        seen,
                    )

    root_types = {
        "query": schema.query_type,
        "mutation": schema.mutation_type,
        "subscription": schema.subscription_type,
    }
    for definition in result.document.definitions:
        if isinstance(definition, OperationDefinitionNode):
            walk(
                definition.selection_set, root_types[definition.operation.value], set()
            )
        elif isinstance(definition, FragmentDefinitionNode):
            walk(
                definition.selection_set,
                schema.type_map.get(definition.type_condition.name.value),
                set(),
            )
    return pairs


def run_download(source: str | None) -> None:
    """Download the schema for one or all environments."""
    from gpp_client2.config import find_download_token
    from gpp_client2.environments import ENVIRONMENTS

    targets = [source] if source else [e.name.lower() for e in ENVIRONMENTS]
    for target in targets:
        try:
            spec = next(e for e in ENVIRONMENTS if e.name.lower() == target)
        except StopIteration:
            raise CodegenError(f"Unknown environment '{target}'.") from None
        if spec.base_url is None:
            print(f"Skipping {target}: no base URL configured yet.")
            continue
        token = find_download_token(target)
        if token is None:
            raise CodegenError(
                f"No token found for '{target}'. Set GPP_TOKEN or add a "
                "profile with this environment to your config file."
            )
        print(f"Downloading {target} schema from {spec.base_url}...")
        sdl = download_schema_sdl(spec.base_url, token)
        path = SCHEMAS_DIR / f"{target}.graphql"
        path.write_text(sdl, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
