fragment ProgramCore on Program {
  id
  name
  existence
  description
}

fragment ProgramDetails on Program {
  ...ProgramCore
  type
  active {
    start
    end
  }
  proposalStatus
  proposal {
    call {
      semester
      active {
        start
        end
      }
      observatory
      gemini {
        type
        instruments
      }
      keck {
        instruments
      }
      subaru {
        type
        instruments
      }
    }
    gemini {
      scienceSubtype
    }
  }
  pi {
    id
  }
}

fragment ProgramGroupElements on Program {
  allGroupElements(includeDeleted: $includeDeleted) {
    parentGroupId
    observation {
      id
      groupId
    }
    group {
      id
      name
      minimumRequired
      ordered
      parentId
      parentIndex
      minimumInterval {
        seconds
      }
      maximumInterval {
        seconds
      }
      system
    }
  }
}
