# Generated by `gqlforge generate`. DO NOT EDIT.
# mypy: ignore-errors

from __future__ import annotations

from typing import Any, Self

import httpx

from ._executor import AsyncExecutor, ExecutorCore, SyncExecutor
from ._ws import AsyncWsTransport, SyncWsTransport, WsConfig, get_ws_url
from .domains import (
    AsyncAttachmentOperations,
    AsyncCallForProposalsOperations,
    AsyncGoatsOperations,
    AsyncObservationOperations,
    AsyncProgramOperations,
    AsyncSchedulerOperations,
    AsyncTargetOperations,
    AsyncWorkflowStateOperations,
    AttachmentOperations,
    CallForProposalsOperations,
    GoatsOperations,
    ObservationOperations,
    ProgramOperations,
    SchedulerOperations,
    TargetOperations,
    WorkflowStateOperations,
)
from .operations import SCHEMA_SOURCES

__all__ = ["AsyncClient", "Client"]


class Client:
    """
    Synchronous client: one attribute per domain.

    Parameters
    ----------
    url : str
        The GraphQL endpoint.
    token : str | None
        Bearer token, sent on HTTP and WebSocket requests.
    source : str | None
        Schema source whose query text to send; defaults to the
        newest (``SCHEMA_SOURCES[0]``).
    read_only : bool
        Refuse to execute mutations before any network call.
    timeout : float
        Request and WebSocket-handshake timeout in seconds.
    headers : dict[str, str] | None
        Extra HTTP headers.
    transport : httpx.BaseTransport | None
        Transport injection, e.g. ``httpx.MockTransport`` in tests.
    ws_url : str | None
        Subscription endpoint; defaults to ``url`` with the scheme
        swapped to ``ws(s)``.
    """

    executor_core_class: type[ExecutorCore] = ExecutorCore
    """Override to specialize payloads, processing, or error types."""

    def __init__(
        self,
        url: str,
        *,
        token: str | None = None,
        source: str | None = None,
        read_only: bool = False,
        timeout: float = 30.0,
        headers: dict[str, str] | None = None,
        transport: Any = None,
        ws_url: str | None = None,
    ) -> None:
        self.source = source or SCHEMA_SOURCES[0]
        request_headers = dict(headers or {})
        if token:
            request_headers["Authorization"] = f"Bearer {token}"
        self._http = httpx.Client(
            base_url=url,
            headers=request_headers,
            timeout=timeout,
            transport=transport,
        )
        core = self.executor_core_class(
            source=self.source, read_only=read_only
        )
        ws = SyncWsTransport(
            WsConfig(
                url=ws_url or get_ws_url(url),
                token=token or "",
                connect_timeout=timeout,
            ),
            core,
        )
        self._executor = SyncExecutor(self._http, core, ws, url=url)
        self._wire_domains()

    def _wire_domains(self) -> None:
        """Attach one API object per domain; override to specialize."""
        self.attachment = AttachmentOperations(self._executor)
        self.call_for_proposals = CallForProposalsOperations(self._executor)
        self.goats = GoatsOperations(self._executor)
        self.observation = ObservationOperations(self._executor)
        self.program = ProgramOperations(self._executor)
        self.scheduler = SchedulerOperations(self._executor)
        self.target = TargetOperations(self._executor)
        self.workflow_state = WorkflowStateOperations(self._executor)

    def graphql(
        self,
        query: str,
        variables: dict[str, Any] | None = None,
        operation_name: str | None = None,
    ) -> Any:
        """Execute a raw operation and return the ``data`` dict."""
        return self._executor.run_raw(query, variables, operation_name)

    def close(self) -> None:
        self._http.close()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()


class AsyncClient:
    """
    Asynchronous client: one attribute per domain.

    Parameters
    ----------
    url : str
        The GraphQL endpoint.
    token : str | None
        Bearer token, sent on HTTP and WebSocket requests.
    source : str | None
        Schema source whose query text to send; defaults to the
        newest (``SCHEMA_SOURCES[0]``).
    read_only : bool
        Refuse to execute mutations before any network call.
    timeout : float
        Request and WebSocket-handshake timeout in seconds.
    headers : dict[str, str] | None
        Extra HTTP headers.
    transport : httpx.BaseTransport | None
        Transport injection, e.g. ``httpx.MockTransport`` in tests.
    ws_url : str | None
        Subscription endpoint; defaults to ``url`` with the scheme
        swapped to ``ws(s)``.
    """

    executor_core_class: type[ExecutorCore] = ExecutorCore
    """Override to specialize payloads, processing, or error types."""

    def __init__(
        self,
        url: str,
        *,
        token: str | None = None,
        source: str | None = None,
        read_only: bool = False,
        timeout: float = 30.0,
        headers: dict[str, str] | None = None,
        transport: Any = None,
        ws_url: str | None = None,
    ) -> None:
        self.source = source or SCHEMA_SOURCES[0]
        request_headers = dict(headers or {})
        if token:
            request_headers["Authorization"] = f"Bearer {token}"
        self._http = httpx.AsyncClient(
            base_url=url,
            headers=request_headers,
            timeout=timeout,
            transport=transport,
        )
        core = self.executor_core_class(
            source=self.source, read_only=read_only
        )
        ws = AsyncWsTransport(
            WsConfig(
                url=ws_url or get_ws_url(url),
                token=token or "",
                connect_timeout=timeout,
            ),
            core,
        )
        self._executor = AsyncExecutor(self._http, core, ws, url=url)
        self._wire_domains()

    def _wire_domains(self) -> None:
        """Attach one API object per domain; override to specialize."""
        self.attachment = AsyncAttachmentOperations(self._executor)
        self.call_for_proposals = AsyncCallForProposalsOperations(self._executor)
        self.goats = AsyncGoatsOperations(self._executor)
        self.observation = AsyncObservationOperations(self._executor)
        self.program = AsyncProgramOperations(self._executor)
        self.scheduler = AsyncSchedulerOperations(self._executor)
        self.target = AsyncTargetOperations(self._executor)
        self.workflow_state = AsyncWorkflowStateOperations(self._executor)

    async def graphql(
        self,
        query: str,
        variables: dict[str, Any] | None = None,
        operation_name: str | None = None,
    ) -> Any:
        """Execute a raw operation and return the ``data`` dict."""
        return await self._executor.run_raw(query, variables, operation_name)

    async def aclose(self) -> None:
        await self._http.aclose()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()
