query getCallForProposalsById($callForProposalsId: CallForProposalsId!) {
  callForProposals(callForProposalsId: $callForProposalsId) {
    ...CallForProposalsDetails
  }
}

query getCallsForProposals(
  $where: WhereCallForProposals
  $offset: CallForProposalsId
  $limit: NonNegInt
  $includeDeleted: Boolean! = false
) {
  callsForProposals(
    WHERE: $where
    OFFSET: $offset
    LIMIT: $limit
    includeDeleted: $includeDeleted
  ) {
    hasMore
    matches {
      ...CallForProposalsDetails
    }
  }
}
