mutation createProgram(
  $properties: ProgramPropertiesInput
  $includeDeleted: Boolean! = false
) {
  createProgram(input: { SET: $properties }) {
    program {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}

mutation updatePrograms(
  $properties: ProgramPropertiesInput!
  $where: WhereProgram
  $limit: NonNegInt
  $includeDeleted: Boolean! = false
) {
  updatePrograms(
    input: {
      SET: $properties
      WHERE: $where
      LIMIT: $limit
      includeDeleted: $includeDeleted
    }
  ) {
    hasMore
    programs {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}

mutation updateProgramById(
  $programId: ProgramId!
  $properties: ProgramPropertiesInput!
  $includeDeleted: Boolean! = false
) {
  updatePrograms(
    input: {
      SET: $properties
      WHERE: { id: { EQ: $programId } }
      LIMIT: 1
      includeDeleted: $includeDeleted
    }
  ) {
    hasMore
    programs {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}

mutation restoreProgramById($programId: ProgramId!, $includeDeleted: Boolean! = true) {
  updatePrograms(
    input: {
      SET: { existence: PRESENT }
      WHERE: { id: { EQ: $programId } }
      LIMIT: 1
      includeDeleted: true
    }
  ) {
    hasMore
    programs {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}

mutation deleteProgramById($programId: ProgramId!, $includeDeleted: Boolean! = false) {
  updatePrograms(
    input: {
      SET: { existence: DELETED }
      WHERE: { id: { EQ: $programId } }
      LIMIT: 1
      includeDeleted: false
    }
  ) {
    hasMore
    programs {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}
