query getProgramById($programId: ProgramId!, $includeDeleted: Boolean! = false) {
  program(programId: $programId) {
    ...ProgramDetails
    ...ProgramGroupElements
  }
}

query getProgramByReference(
  $programReference: ProgramReferenceLabel!
  $includeDeleted: Boolean! = false
) {
  program(programReference: $programReference) {
    ...ProgramDetails
    ...ProgramGroupElements
  }
}

query getProgramByProposalReference(
  $proposalReference: ProposalReferenceLabel!
  $includeDeleted: Boolean! = false
) {
  program(proposalReference: $proposalReference) {
    ...ProgramDetails
    ...ProgramGroupElements
  }
}

query getPrograms(
  $where: WhereProgram
  $offset: ProgramId
  $limit: NonNegInt
  $includeDeleted: Boolean! = false
) {
  programs(
    WHERE: $where
    OFFSET: $offset
    LIMIT: $limit
    includeDeleted: $includeDeleted
  ) {
    hasMore
    matches {
      ...ProgramDetails
      ...ProgramGroupElements
    }
  }
}
