mutation createObservation($input: CreateObservationInput!) {
  createObservation(input: $input) {
    observation {
      ...ObservationDetails
    }
  }
}

mutation cloneObservation($input: CloneObservationInput!) {
  cloneObservation(input: $input) {
    newObservation {
      ...ObservationDetails
    }
  }
}

mutation updateObservations($input: UpdateObservationsInput!) {
  updateObservations(input: $input) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation updateObservationById(
  $observationId: ObservationId!
  $properties: ObservationPropertiesInput!
) {
  updateObservations(
    input: { SET: $properties, WHERE: { id: { EQ: $observationId } }, LIMIT: 1 }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation updateObservationByReference(
  $observationReference: NonEmptyString!
  $properties: ObservationPropertiesInput!
) {
  updateObservations(
    input: {
      SET: $properties
      WHERE: { reference: { label: { EQ: $observationReference } } }
      LIMIT: 1
    }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation restoreObservationById($observationId: ObservationId!) {
  updateObservations(
    input: {
      SET: { existence: PRESENT }
      WHERE: { id: { EQ: $observationId } }
      LIMIT: 1
      includeDeleted: true
    }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation restoreObservationByReference($observationReference: NonEmptyString!) {
  updateObservations(
    input: {
      SET: { existence: PRESENT }
      WHERE: { reference: { label: { EQ: $observationReference } } }
      LIMIT: 1
      includeDeleted: true
    }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation deleteObservationById($observationId: ObservationId!) {
  updateObservations(
    input: {
      SET: { existence: DELETED }
      WHERE: { id: { EQ: $observationId } }
      LIMIT: 1
    }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}

mutation deleteObservationByReference($observationReference: NonEmptyString!) {
  updateObservations(
    input: {
      SET: { existence: DELETED }
      WHERE: { reference: { label: { EQ: $observationReference } } }
      LIMIT: 1
    }
  ) {
    hasMore
    observations {
      ...ObservationDetails
    }
  }
}
