query getGoatsPrograms {
  programs(includeDeleted: false, WHERE: { proposalStatus: { EQ: ACCEPTED } }) {
    matches {
      id
      name
      description
      reference {
        label
      }
      proposalStatus
      type
    }
    hasMore
  }
}
query getGoatsObservations($programId: ProgramId!) {
  observations(
    includeDeleted: false
    WHERE: { program: { id: { EQ: $programId }, proposalStatus: { EQ: ACCEPTED } } }
  ) {
    matches {
      id
      reference {
        label
      }
      instrument
      title
      constraintSet {
        imageQuality
        cloudExtinction
        skyBackground
        waterVapor
        elevationRange {
          airMass {
            min
            max
          }
          hourAngle {
            minHours
            maxHours
          }
        }
      }
      workflow {
        calculationState
        value {
          state
          validTransitions
          validationErrors {
            code
          }
        }
      }
      attachments {
        id
        attachmentType
        fileName
        description
        updatedAt
      }
      timingWindows {
        inclusion
        startUtc
        end {
          ... on TimingWindowEndAt {
            atUtc
          }
          ... on TimingWindowEndAfter {
            after {
              seconds
            }
            repeat {
              period {
                seconds
              }
              times
            }
          }
        }
      }
      targetEnvironment {
        asterism {
          id
          name
          opportunity {
            __typename
          }
        }
        firstScienceTarget {
          id
          name
          opportunity {
            __typename
          }
          sidereal {
            ra {
              hms
              hours
              degrees
            }
            dec {
              dms
              degrees
            }
            properMotion {
              ra {
                milliarcsecondsPerYear
              }
              dec {
                milliarcsecondsPerYear
              }
            }
            parallax {
              milliarcseconds
            }
            radialVelocity {
              kilometersPerSecond
            }
          }
          sourceProfile {
            point {
              bandNormalized {
                brightnesses {
                  band
                  value
                  units
                }
                sed {
                  blackBodyTempK
                  coolStar
                  fluxDensities {
                    wavelength {
                      nanometers
                    }
                    density
                  }
                  fluxDensitiesAttachment
                  galaxy
                  hiiRegion
                  planet
                  planetaryNebula
                  powerLaw
                  quasar
                  stellarLibrary
                }
              }
            }
          }
        }
      }
      posAngleConstraint {
        mode
        angle {
          degrees
        }
      }
      scienceBand
      observationDuration {
        seconds
        minutes
        hours
        iso
      }
      observerNotes
      scienceRequirements {
        mode
        spectroscopy {
          wavelength {
            nanometers
          }
        }
        exposureTimeMode {
          signalToNoise {
            value
            at {
              nanometers
            }
          }
          timeAndCount {
            time {
              seconds
            }
            count
            at {
              nanometers
            }
          }
        }
      }
      observingMode {
        instrument
        mode
        gmosNorthLongSlit {
          grating
          filter
          fpu
          centralWavelength {
            nanometers
          }
          wavelengthDithers {
            nanometers
          }
          xBin
          yBin
          ampReadMode
          roi
          exposureTimeMode {
            signalToNoise {
              value
              at {
                nanometers
              }
            }
            timeAndCount {
              time {
                seconds
              }
              count
              at {
                nanometers
              }
            }
          }
          offsets {
            arcseconds
          }
        }
        gmosSouthLongSlit {
          grating
          filter
          fpu
          centralWavelength {
            nanometers
          }
          wavelengthDithers {
            nanometers
          }
          xBin
          yBin
          ampReadMode
          roi
          exposureTimeMode {
            signalToNoise {
              value
              at {
                nanometers
              }
            }
            timeAndCount {
              time {
                seconds
              }
              count
              at {
                nanometers
              }
            }
          }
          offsets {
            arcseconds
          }
        }
        gmosNorthImaging {
          filters {
            filter
            exposureTimeMode {
              signalToNoise {
                value
                at {
                  nanometers
                }
              }
              timeAndCount {
                time {
                  seconds
                }
                count
                at {
                  nanometers
                }
              }
            }
          }
          ampReadMode
          bin
          roi
          variant {
            variantType
            grouped {
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              order
              offsets {
                generatorType
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
              }
            }
            interleaved {
              offsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
            }
            preImaging {
              offset1 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset2 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset3 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset4 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
            }
          }
        }
        gmosSouthImaging {
          filters {
            filter
            exposureTimeMode {
              signalToNoise {
                value
                at {
                  nanometers
                }
              }
              timeAndCount {
                time {
                  seconds
                }
                count
                at {
                  nanometers
                }
              }
            }
          }
          ampReadMode
          bin
          roi
          variant {
            variantType
            grouped {
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              order
              offsets {
                generatorType
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
              }
            }
            interleaved {
              offsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                  center {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
            }
            preImaging {
              offset1 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset2 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset3 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset4 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
            }
          }
          ampReadMode
          bin
          roi
          variant {
            variantType
            grouped {
              offsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              order
            }
            interleaved {
              offsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
              skyCount
              skyOffsets {
                generatorType
                enumerated {
                  values {
                    guiding
                    offset {
                      p {
                        arcseconds
                      }
                      q {
                        arcseconds
                      }
                    }
                  }
                }
                random {
                  seed
                  size {
                    arcseconds
                  }
                }
                spiral {
                  seed
                  size {
                    arcseconds
                  }
                }
                uniform {
                  cornerA {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                  cornerB {
                    p {
                      arcseconds
                    }
                    q {
                      arcseconds
                    }
                  }
                }
              }
            }
            preImaging {
              offset1 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset2 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset3 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
              offset4 {
                p {
                  arcseconds
                }
                q {
                  arcseconds
                }
              }
            }
          }
        }
      }
      program {
        allocations {
          scienceBand
          duration {
            hours
          }
        }
        timeCharge {
          band
          time {
            program {
              hours
            }
          }
        }
      }
    }
    hasMore
  }
}
